# Generated by Django 3.2.5 on 2022-03-24 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_app', '0002_auto_20220324_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='name',
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
