# Generated by Django 3.2.9 on 2022-03-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='student_id',
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_app.student'),
        ),
    ]
