# Generated by Django 3.2.9 on 2022-03-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_auto_20220324_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_app.institution'),
        ),
    ]
