# Generated by Django 3.2.5 on 2022-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_auto_20220324_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
