# Generated by Django 3.2.5 on 2022-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_student_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
